### ISSUE TITLE
"Book" folder missing?

### ISSUE THREAD

**Issue by Pascal-H** [codeZeilen/SqueakByExample-english#16] opened 2019-10-30 15:01 UTC
In the readme file, in the section [Makefile](https://github.com/SquareBracketAssociates/SqueakByExample-english#makefile), it says that you can just navigate into the "Book folder" and run `make`. In the current version, I don't see any book folder and when running `make` in the main folder, I get `Makefile:26: recipe for target 'book' failed`.

**Comment by codeZeilen** [comment] 2019-10-30 16:34
Good point. The Makefile is (currently) optimized for running on the CI server. You can run it locally by changing lines 14 and 15 to:

```
PDFLATEX = pdflatex -file-line-error
BIBTEX=bibtex
```

**Comment by codeZeilen** [comment] 2019-10-30 16:46
Should be resolved by 291602b

**Comment by Pascal-H** [comment] 2019-10-30 17:36
Thanks :smiley: That resolved the first part of the problem, but it continues :yum: 
If I run `make`, I get:
```
cp -fR SmalltalkSources ListingSources
cp: cannot create directory 'ListingSources/SmalltalkSources': Permission denied
Makefile:61: recipe for target 'listings' failed
make: *** [listings] Error 1
```

If I run `sudo make`, the script expects an input, indicated with a `?`. No idea, what I should enter :sweat_smile: :
```
LaTeX Warning: Reference `fig:download' on page 3 undefined on input line 74.

[3]

./QuickTour/QuickTour.tex:115: LaTeX Error: File `startup' not found.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.115 ...cludegraphics[width=\textwidth]{startup}}
                                                  
? 
```

**Comment by Pascal-H** [comment] 2019-10-30 17:38
Ah, if I just press `enter` it jumps forward to the next prompt and so on for some time. Then the make script finishes with:
```
Output written on SBE.pdf (278 pages, 3906642 bytes).
Transcript written on SBE.log.
Command exited with non-zero status 1
7.29user 0.23system 4:46.63elapsed 2%CPU (0avgtext+0avgdata 54120maxresident)k
0inputs+8496outputs (0major+11916minor)pagefaults 0swaps
Makefile:30: recipe for target 'book' failed
make: *** [book] Error 1
```

**Comment by LinqLover** [comment] 2019-11-01 17:28
Hi Pascal, please have a look at our [.travis.yml file](https://github.com/codeZeilen/SqueakByExample-english/blob/master/.travis.yml#L8-L10), which describes the actual build in the `script` section.

Our total build process looks like this:
1. Using [smalltalkCI](https://github.com/hpi-swa/smalltalkCI), the [SBEExecuteExtractTest](https://github.com/codeZeilen/SqueakByExample-english/tree/master/SmalltalkSources/SBE-Extract.package/SBEExecuteExtractTest.class) is run which basically scans all .tex files in the repo for `%%{SBESqueakPicture writeTo: ...` sections and evaluates them. This way nearly all screenshot in the book (at least these one in Part I) are generated automatically.
 (Please note that I'm currently reworking the code base for that step, I will have finished in a few days)
2. The Makefile is executed and, inter alia, compiles the PDF, relying on the existence of the generated PNG files.

I'm sorry we do not support a completely make-supported build at the moment, but if you would like to reproduce the build locally, you will need to clone our repo using [Squot](https://github.com/hpi-swa/Squot) and run the `SBEExecuteExtractTest`. Be sure to set [`SBESqueakPicture resourceDirectory`](https://github.com/codeZeilen/SqueakByExample-english/blob/master/SmalltalkSources/SBE-Extract.package/SBESqueakPicture.class/class/resourceDirectory..st) to the path where the tex files are located, before, as Squot does not write the working copy into the filesystem.

**Comment by LinqLover** [comment] 2019-12-06 22:20
I think this issue can be closed? Otherwise, please answer!

**Closed by LinqLover** 2019-12-06 22:20 UTC
